title: Terraced Terrain Generator (TTG)
tagline: Terraced Terrain Generator (TTG)
description: Terraced Terrain Generator (TTG) is a Unity tool for procedural generation of terraced terrains.
baseurl: /
url: ttg.matheusamazonas.net
theme: minima
homepage: /index.html
sass:
  style: compressed