title: Terraced Terrain Generator (TTG)
baseurl: /
url: https://ttg.matheusamazonas.net
homepage: /index.html
sass:
  style: compressed

# Author
author:
  name: Matheus Amazonas
  website: https://matheusamazonas.net

# Build settings
remote_theme: jekyll/minima@fdc3aba23a1d59ad1d1f65f505693848c4b82fdf
plugins:
  - jekyll-remote-theme
  - jekyll-target-blank

# Theme settings
minima:
  skin: dark